import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Topsale from "./component/navbar1 copy";
import Footer from "./component/footer";
import {
  ClerkProvider,
} from '@clerk/nextjs'
;
import Navbar from "./component/navbar1";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html>
        <body>
          {/* Hide Topsale on mobile */}
          <div className="hidden lg:block">
            <Topsale />
          </div>
           <Navbar/>
          {children}
         
          <Footer />
        </body>
      </html>
      </ClerkProvider>
     
      
   
  );
}
